/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MotocicletaController;
import DTOs.MotocicletaDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class VistaMotocicleta extends javax.swing.JFrame {

    private MotocicletaController motocicletaController = new MotocicletaController();
            
    
    /**
     * Creates new form VistaMotocicleta
     */
    public VistaMotocicleta() {
        initComponents();
        listarTabla();
    }
    
    private void listarTabla(){
       DefaultTableModel model = new DefaultTableModel();
       model.setColumnIdentifiers(new Object[]{"Id", "Marca", "Cilindraje", "Precio", "Color"});
       
       ArrayList<MotocicletaDTO> lista;
        try {
            lista = motocicletaController.listarTodos();
            for (int i = 0; i < lista.size(); i++) {
                MotocicletaDTO dto = lista.get(i);
                model.addRow(new Object[]{
                    dto.getId(),
                    dto.getMarca(),
                    dto.getCilindraje(),
                    dto.getPrecio(),
                    dto.getColor()
                });
            }
            tabla.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error al cargar los datos");
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtMarca = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimiar(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        txtMarca.setBorder(javax.swing.BorderFactory.createTitledBorder("Marca"));

        txtCilindraje.setBorder(javax.swing.BorderFactory.createTitledBorder("Cilindraje"));

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));

        txtColor.setBorder(javax.swing.BorderFactory.createTitledBorder("Color"));

        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(txtCilindraje, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPrecio)
                        .addComponent(txtColor))
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar
        // TODO add your handling code here:
        
        String marca = txtMarca.getText();
        String cilin = txtCilindraje.getText();
        String preci = txtPrecio.getText();
        String color = txtColor.getText();
        
        try {
            
            int cilindraje = Integer.parseInt(cilin);
            double precio = Double.parseDouble(preci);
            MotocicletaDTO dto = new MotocicletaDTO(0, marca, cilindraje, precio, color);
            
            boolean exito = motocicletaController.registrarMotocicleta(dto);
            if(exito){
                JOptionPane.showMessageDialog(null, "se registro exitosamente");
                listarTabla();
            }else{
                JOptionPane.showMessageDialog(null, "hubo un error, la motocicleta no se pudo registrar");
            }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "ingrese los numeros correctamente");
        }
        catch (SQLException ex) {
            Logger.getLogger(VistaLoguin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ocurrio un error sql");
        }
    }//GEN-LAST:event_btnGuardar

    private void btnEditar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar
        // TODO add your handling code here:
        String marca = txtMarca.getText();
        String cilin = txtCilindraje.getText();
        String preci = txtPrecio.getText();
        String color = txtColor.getText();
        String id = txtId.getText();
        
        try {
            
            int idEditar =  Integer.parseInt(id);
            int cilindraje = Integer.parseInt(cilin);
            double precio = Double.parseDouble(preci);
            MotocicletaDTO dto = new MotocicletaDTO(idEditar, marca, cilindraje, precio, color);
            
            boolean exito = motocicletaController.actualizarMotocicleta(dto);
            if(exito){
                JOptionPane.showMessageDialog(null, "se actualizo exitosamente");
                listarTabla();
            }else{
                JOptionPane.showMessageDialog(null, "hubo un error, la motocicleta no se pudo editar");
            }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "ingrese los numeros correctamente");
        }
        catch (SQLException ex) {
            Logger.getLogger(VistaLoguin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ocurrio un error sql");
        }
    }//GEN-LAST:event_btnEditar

    private void btnElimiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimiar
        // TODO add your handling code here:
        
        String id = txtId.getText();
        
        try {
            int idEliminar = Integer.parseInt(id);
            boolean exito = motocicletaController.eliminarMotocicleta(idEliminar);
            if(exito){
                JOptionPane.showMessageDialog(null, "se elimino exitosamente");
                listarTabla();
            }else{
                JOptionPane.showMessageDialog(null, "hubo un error, la motocicleta no se pudo eliminar");
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(VistaLoguin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ocurrio un error sql");
        }
    }//GEN-LAST:event_btnElimiar

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
